name: setup-frontend
description: Sets up runner environment for frontend code


inputs:
  cache-version:
    description: Cache version used for invalidation. Example '1'
    default: '1'
    required: false
    type: string
  node-version:
    description: Node.js version to use. Example '12'
    default: '12'
    required: false
    type: string


runs:
  using: composite
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}

    - name: set helper variable
      shell: bash
      run: echo "${name}=${value}" >> $GITHUB_ENV
      env:
        name: my_cache_prefix
        value: ${{ runner.os }}-node${{ inputs.node-version }}-cache${{ inputs.cache-version }}

    - name: set helper variable
      shell: bash
      run: echo "${name}=$(${value})" >> $GITHUB_ENV
      env:
        name: my_yarn_cache_path
        value: yarn cache dir

    - uses: actions/cache@v2
      id: cache-lockfile
      with:
        path: |
          **/node_modules
          ${{ env.my_yarn_cache_path }}
        key: ${{ env.my_cache_prefix }}-lockfile-${{ hashFiles('**/yarn.lock') }}
        restore-keys: ${{ env.my_cache_prefix }}-lockfile-

    - name: conditionally install dependencies
      shell: bash
      if: steps.cache-lockfile.outputs.cache-hit != 'true'
      working-directory: ./frontend
      run: >
        yarn install
        --frozen-lockfile
        --non-interactive
        --prefer-offline
        --ignore-scripts
