name: pack-backend
description: Packs backend for deployment and uploads artifact


runs:
  using: composite
  steps:
    - uses: turskislab/.github/.github/actions/set-env-var@v1
      with:
        name: my_installed_packages_path
        command: pipenv run python -c 'import site; print(site.getsitepackages()[0])'

    - name: pack dependencies
      shell: bash
      working-directory: ./backend
      run: 7z a ../lambda.zip "${{ env.my_installed_packages_path }}"

    - name: pack source code
      shell: bash
      working-directory: ./backend
      run: 7z a ../lambda.zip -xr'!.venv' migrations ../backend

    - uses: actions/upload-artifact@v3
      with:
        name: backend
        path: lambda.zip
        retention-days: 1
        if-no-files-found: error
