name: set-env-var
description: Sets a environment variable for later use


inputs:
  name:
    description: Name of the variable
    required: true
    type: string
  value:
    description: Value of the variable
    default: ""
    required: false
    type: string
  command:
    description: Command to use for value
    default: ""
    required: false
    type: string


runs:
  using: composite
  steps:
    - name: conditionally run specified command
      shell: bash
      id: command
      if: inputs.command != ''
      run: echo "::set-output name=stdout::$(${{ inputs.command }})"

    - name: save value to environment variable
      shell: bash
      run: echo "${name}=${value}" >> $GITHUB_ENV
      env:
        name: ${{ inputs.name }}
        value: ${{ inputs.value || steps.command.outputs.stdout }}